config/routes.rb
Ationsg::Application.routes.draw do

  scope "(:locale)", locale: /en|zh-CN/ do
    # devise
    devise_scope :user do
      # oauth
      get 'users/oauth_bind' => 'oauth_bind#new_from_oauth', as: :oauth_bind_new
      post 'users/oauth_bind' => 'oauth_bind#bind_with_oauth'

      # registration
      get 'users/sign_up' => 'devise/registrations#new', as: :new_user_registration
      post 'users' => 'devise/registrations#create', as: :user_registration
    end

    # products
    resources :products, only: [:show] do
      get 'like' => 'products#like', as: :like
      get 'unlike' => 'products#unlike', as: :unlike
    end

    resources :comments, only: [:show, :new, :create]

    # categories
    resources :categories, only: [:show]

    # cart
    get 'cart' => 'cart#show', as: :cart
    get 'cart/partial' => 'cart#partial', as: :cart_partial

    # orders
    resources :orders, only: [:new, :create, :show]
    get 'orders/:id/pay' => 'orders#pay', as: :pay_order

    # payments
    # resources :payments, only: [:create]
    get 'payments/new/order/:order_id/method/:method' => 'payments#create', as: :create_payment

    # cards
    get 'cards/:card_id/recharge' => 'recharge_payments#new', as: :recharge_card
    resources :recharge_payments, only: [:new, :create]

    # my
    get 'my' => 'my#info'
    get 'my/info' => 'my#info', as: :my_info
    patch 'my/info' => 'my#info_update', as: :udpate_my_info
    get 'my/orders' => 'my#orders', as: :my_orders
    get 'my/addresses' => 'my#addresses', as: :my_addresses
    get 'my/payments' => 'my#payments', as: :my_payments
    get 'my/liked' => 'my#liked', as: :my_liked
    get 'my/comments' => 'my#comments', as: :my_comments
    get 'my/cards' => 'my#cards', as: :my_cards

    # static pages & root
    resources :pages, only: [:show]

  end

  # admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # omniauth doesnot support dynamic routing with locale
  devise_for :users, controllers: { omniauth_callbacks: 'authentications' }, skip: [:registrations]

  get "/:locale" => 'pages#show', id: 'home'
  root 'pages#show', id: 'home'  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  # attachment
  has_many :images, as: :imageable
  accepts_nested_attributes_for :images, allow_destroy: true

  # validation
  validates :comment, length: { in: 20..200 }
  validates :user, presence: true

  def product
    (Object.const_get commentable_type).find(commentable_id)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def create
    @product = Product.find params['product_id']
    @comment = @product.comments.create( comment_attributes )
    @comment.user = current_user
    if not @comment.valid?
      @comment.errors.full_messages.each do |m|
        (flash[:alert] ||= []) << m
      end
    else
      @comment.save!
    end
    redirect_to product_path @product
  end

  private

  def comment_attributes
    # params['comment'].permit(:comment, images_attributes: [:_destroy, :id, :attachment])
    # TODO _destroy and id
    params['comment'].permit(:comment, images_attributes: [:attachment])
  end
end

app/views/comments/_new.html.haml
= form_for @new_comment, url: comments_path(@new_comment), html: {class: 'comment new form-horizontal', multipart: true} do |f|
  = hidden_field_tag :product_id, @product.id
  .form-group
    = f.label :comment, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :comment, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      .btn-group
        - @new_comment.images.build
        %button.btn.btn-default{type: 'button'}
          .field-for-input-file
            = f.fields_for :images do |i|
              = i.file_field :attachment
          = t 'comments.new.upload_photo'
        = f.submit (t 'common.submit'), class: 'btn btn-default'

/ = semantic_form_for @new_comment, url: comments_path(@new_comment), html: {multipart: true} do |f|
/   = hidden_field_tag :product_id, @product.id

/   = f.input :comment

/   - @new_comment.images.build
/   = f.semantic_fields_for :images do |i|
/     = i.input :attachment , as: :file
/   = f.action :submit

app/views/comments/_show.html.haml
- comment_token = SecureRandom.hex(10)
- product = comment.product
.comments-show
  - if (defined? show_product_cover) and show_product_cover
    %aside.product-cover
      %a{style: "background-image: url(#{background_image_url product.cover})", href: product_path(product)}

  .content
    %header.author
      = User.model_name.human
      = comment.user.name
      = t 'common.time.created_at'
      = t 'common.time.ago', time: ( time_ago_in_words (Time.now - comment.updated_at).seconds.from_now )
      
    %p
      = comment.comment

    %ul.images.list-unstyled.list-inline
      - comment.images.each_with_index do |image, index|
        %li
          %a.image{style: "background-image: url(#{background_image_url image.url})", data: {toggle: 'modal', target: "#comment-#{comment_token}-image-#{index}"}}

          .comment-image.modal.fade{id: "comment-#{comment_token}-image-#{index}", tabindex: '-1'}
            .modal-dialog.modal-lg
              .modal-content
                = image_tag image.url

    %footer.detail
      .element.like
        %i.fa.fa-fw.fa-heart
        10
      .element.share
        %a
          %i.fa.fa-fw.fa-share-alt
        .links
          / TODO currently share product instead of comment
          = link_to product_share_url(product, 'googleplus'), target: '_blank', onclick: popup_script do
            %i.fa.fa-fw.fa-google-plus
          = link_to product_share_url(product, 'facebook'), target: '_blank', onclick: popup_script do
            %i.fa.fa-fw.fa-facebook