config/routes.rb
Ationsg::Application.routes.draw do

  scope "(:locale)", locale: /en|zh-CN/ do
    # devise
    devise_scope :user do
      # oauth
      get 'users/oauth_bind' => 'oauth_bind#new_from_oauth', as: :oauth_bind_new
      post 'users/oauth_bind' => 'oauth_bind#bind_with_oauth'

      # registration
      get 'users/sign_up' => 'devise/registrations#new', as: :new_user_registration
      post 'users' => 'devise/registrations#create', as: :user_registration
    end

    # products
    resources :products, only: [:show] do
      get 'like' => 'products#like', as: :like
      get 'unlike' => 'products#unlike', as: :unlike
    end

    resources :comments, only: [:show, :new, :create]

    # categories
    resources :categories, only: [:show]

    # cart
    get 'cart' => 'cart#show', as: :cart
    get 'cart/partial' => 'cart#partial', as: :cart_partial

    # orders
    resources :orders, only: [:new, :create, :show]
    get 'orders/:id/pay' => 'orders#pay', as: :pay_order

    # payments
    # resources :payments, only: [:create]
    get 'payments/new/order/:order_id/method/:method' => 'payments#create', as: :create_payment

    # cards
    get 'cards/:card_id/recharge' => 'recharge_payments#new', as: :recharge_card
    resources :recharge_payments, only: [:new, :create]

    # my
    get 'my' => 'my#info'
    get 'my/info' => 'my#info', as: :my_info
    patch 'my/info' => 'my#info_update', as: :udpate_my_info
    get 'my/orders' => 'my#orders', as: :my_orders
    get 'my/addresses' => 'my#addresses', as: :my_addresses
    get 'my/payments' => 'my#payments', as: :my_payments
    get 'my/liked' => 'my#liked', as: :my_liked
    get 'my/comments' => 'my#comments', as: :my_comments
    get 'my/cards' => 'my#cards', as: :my_cards

    # static pages & root
    resources :pages, only: [:show]

  end

  # admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # omniauth doesnot support dynamic routing with locale
  devise_for :users, controllers: { omniauth_callbacks: 'authentications' }, skip: [:registrations]

  get "/:locale" => 'pages#show', id: 'home'
  root 'pages#show', id: 'home'  

end

app/views/shared/_flash.html.erb
<% if not flash.empty? %>
  <% bptype = {notice: 'info', "notice" => 'info', alert: 'warning', "alert" => 'warning'} %>
  <div class="container flash">
    <% flash.each do |type, msgs| -%>
      <% if msgs.kind_of?(Array) %>
        <% msgs.each do |msg| %>
          <div class="alert alert-<%= bptype[type] %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= msg %>
          </div>
        <% end -%>
      <% else %>
        <div class="alert alert-<%= bptype[type] %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= msgs %>
        </div>        
      <% end %>
    <% end -%>
  </div>  
<% end %>

app/views/shared/_footer.html.haml
%footer.main
  .logo
    = image_tag 'logo.png'
  .links
    %ul
      %li
        %h3
          %i.fa.fa-fw.fa-angle-down
          = t 'pages.about_us'
      -['about_us', 'contact_us'].each do |p|
        %li
          =link_to page_path(p) do
            %i.fa.fa-fw.fa-angle-right
            = t("pages.#{p}")
    %ul
      %li
        %h3
          %i.fa.fa-fw.fa-angle-down
          = t 'pages.follow_us'
      %li
        = link_to 'TODO' do
          %i.fa.fa-fw.fa-twitter
          Twitter
      %li
        = link_to 'TODO' do
          %i.fa.fa-fw.fa-facebook
          Facebook
      %li
        = link_to 'TODO' do
          %i.fa.fa-fw.fa-google-plus
          Google+
    %ul
      %li
        %h3
          %i.fa.fa-fw.fa-angle-down
          = t 'pages.help_center'
      %li
        = link_to page_path('help_center') do
          %i.fa.fa-fw.fa-question
          = t 'pages.help_center'

  %hr
    %p Disclaimer area lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, nostrum repudiandae saepe.
    %br
    %p Copyright Ation.sg 2014

= render 'shared/scripts'

app/views/shared/_navbar.html.erb
<header class="container main">

  <div class="logo">
    <%= link_to main_app.root_path do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>

  <div class="to-stick" data-spy="affix" data-offset-top="200">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">TODO Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= main_app.root_path %>">
            <%= image_tag 'logo.png' %>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% Category.all.each do |c| %>
                  <li>
                    <%= link_to c.name, main_app.category_path(c) %>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right user">
            <%= render partial: 'shared/navbar_user' %>
          </ul>

          <ul class="nav navbar-nav navbar-right cart">
            <%= render partial: 'shared/navbar_cart'  %>
          </ul>

          <ul class="nav navbar-nav navbar-right locale">
            <li>
              <% case I18n.locale %>
              <% when :en %>
                <%= link_to url_for(locale: 'zh-CN') do %>
                  <i class="fa fa-language"></i> 简体中文
                <% end %>
              <% when 'zh-CN'.to_sym %>
                <%= link_to url_for(locale: 'en') do %>
                  <i class="fa fa-language"></i> English
                <% end %>
              <% end %>
            </li>
          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>    
  </div>

</header>


app/views/shared/_navbar_cart.html.haml
%li.dropdown
  / this delay object in data doesn't work
  %a.cart-btn.dropdown-toggle{data: {toggle: 'dropdown'}}
    %span.glyphicon.glyphicon-shopping-cart= "(#{@cart.size})"
    %b.caret
  .cart-wrapper.dropdown-menu
    = render partial: 'cart/navbar_partial', locals: { cart: @cart }, layout: false

app/views/shared/_navbar_user.html.erb
<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <span class="glyphicon glyphicon-user"></span>
      <%= current_user.name %>
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to t('nav.my_orders'), main_app.my_orders_path %></li>
      <li><%= link_to t('nav.my_info'), main_app.my_info_path %></li>
<!--  TODO
      <li><%= link_to t('nav.my_addresses'), main_app.my_addresses_path %></li>
      <li><%= link_to t('nav.my_payments'), main_app.my_payments_path %></li>
-->
      <li><%= link_to t('nav.my_liked'), main_app.my_liked_path %></li>
      <li><%= link_to t('nav.my_comments'), main_app.my_comments_path %></li>
      <li><%= link_to t('nav.my_cards'), main_app.my_cards_path %></li>
      <li class="divider"></li>
      <li><%= link_to t('devise.navigation.sign_out'), destroy_user_session_path, {:method => "DELETE"} %></li>
    </ul>
  </li>
<% else %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <span class="glyphicon glyphicon-user"></span>
      <%= t 'devise.navigation.not_signed_in' %>
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <%= form_for :user, url: session_path(:user) do |f| %>
        <%= f.text_field :email, placeholder: 'Email' %>
        <%= f.text_field :password, placeholder: 'Password' %>
        <div class="btn-group-vertical">
          <%= f.submit t('devise.navigation.sign_in'), class: 'btn btn-sm btn-primary btn-block' %>
          <a class="btn btn-social btn-google-plus" href="<%= user_omniauth_authorize_path :gplus %>">
           <i class="fa fa-google-plus"></i> <%= t 'devise.navigation.sign_in_with_provider', provider: t('devise.authentications.providers.gplus') %>
          </a>
          <a class="btn btn-social btn-facebook" href="<%= user_omniauth_authorize_path :facebook %>">
           <i class="fa fa-facebook"></i> <%= t 'devise.navigation.sign_in_with_provider', provider: t('devise.authentications.providers.facebook') %>
          </a>
        </div>
      <% end %>
      <li><%# link_to t('devise.navigation.sign_up'), new_user_registration_path %></li>
    </ul>
  </li>
<% end %>

app/views/shared/_scripts.html.erb
<!-- GA -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50629091-1', 'ation.sg');
  ga('send', 'pageview');
</script>
<!-- GA END -->

<% if controller_name.in? ['products'] %>
  <%= javascript_include_tag controller_name %>
<% end %>

<% if controller_name.in? ['products'] %>
  <%= javascript_include_tag 'img_slide' %>
<% end %>

app/views/shared/footer.html.erb
footer.html.erb

app/views/shared/navbar.html.erb
navbar.html.erb