config/routes.rb
Ationsg::Application.routes.draw do

  scope "(:locale)", locale: /en|zh-CN/ do
    # devise
    devise_scope :user do
      # oauth
      get 'users/oauth_bind' => 'oauth_bind#new_from_oauth', as: :oauth_bind_new
      post 'users/oauth_bind' => 'oauth_bind#bind_with_oauth'

      # registration
      get 'users/sign_up' => 'devise/registrations#new', as: :new_user_registration
      post 'users' => 'devise/registrations#create', as: :user_registration
    end

    # products
    resources :products, only: [:show] do
      get 'like' => 'products#like', as: :like
      get 'unlike' => 'products#unlike', as: :unlike
    end

    resources :comments, only: [:show, :new, :create]

    # categories
    resources :categories, only: [:show]

    # cart
    get 'cart' => 'cart#show', as: :cart
    get 'cart/partial' => 'cart#partial', as: :cart_partial

    # orders
    resources :orders, only: [:new, :create, :show]
    get 'orders/:id/pay' => 'orders#pay', as: :pay_order

    # payments
    # resources :payments, only: [:create]
    get 'payments/new/order/:order_id/method/:method' => 'payments#create', as: :create_payment

    # cards
    get 'cards/:card_id/recharge' => 'recharge_payments#new', as: :recharge_card
    resources :recharge_payments, only: [:new, :create]

    # my
    get 'my' => 'my#info'
    get 'my/info' => 'my#info', as: :my_info
    patch 'my/info' => 'my#info_update', as: :udpate_my_info
    get 'my/orders' => 'my#orders', as: :my_orders
    get 'my/addresses' => 'my#addresses', as: :my_addresses
    get 'my/payments' => 'my#payments', as: :my_payments
    get 'my/liked' => 'my#liked', as: :my_liked
    get 'my/comments' => 'my#comments', as: :my_comments
    get 'my/cards' => 'my#cards', as: :my_cards

    # static pages & root
    resources :pages, only: [:show]

  end

  # admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # omniauth doesnot support dynamic routing with locale
  devise_for :users, controllers: { omniauth_callbacks: 'authentications' }, skip: [:registrations]

  get "/:locale" => 'pages#show', id: 'home'
  root 'pages#show', id: 'home'  

end

app/models/card.rb
class Card < ActiveRecord::Base
  # validations
  validates :balance, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # associations
  belongs_to :user

  def pay(amount)
    return false unless self.balance >= amount
    self.balance -= amount
    self.save
  end

  def recharge(amount)
    self.balance += amount
    self.save!
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
end

app/views/shared/cards/_cart_item.html.haml
- case cart_item[:type]
- when 'product'
  .cart-item-card
    .image
      = image_tag cart_item[:product].cover
    .content
      %h1= cart_item[:product].name
      / %p= cart_item[:product].description.truncate(100)
      %p.detail= to_sg_dollar cart_item[:product].price
    - if defined? show_remove_btn and show_remove_btn
      .remove
        %i.fa.fa-minus{data: {index: index}}

app/views/shared/cards/_category.html.erb
<!-- = link_to(main_app.category_path(category), class: 'thumbnail thumbnail-common thumbnail-category') do
  = image_tag('http://placehold.it/200x200', size: '600x600')
 -->
<div class="category-card">
  <div class="icon">
    <!-- TODO, category cover img -->
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_2.png" alt="">
  </div>
  <div class="content">
    <h2><%= category.name %></h2>
    <p>Lorem dolor sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla.</p>
    <footer class="pull-right">
      <%= link_to t('categories.card.see_all'), main_app.category_path(category) %>
    </footer>
  </div>
</div>

app/views/shared/cards/_order.html.haml
- order_token = SecureRandom.hex(10)
.order-card.panel.panel-default
  .panel-heading
    .panel-title
      %a{"data-parent" => ".order-cards", "data-toggle" => "collapse", href: "#order-card-#{order_token}"}
        %i.fa.fa-caret-square-o-down
          = to_sg_dollar order.cart[:total_price]
          ,
          = t 'common.time.created_at'
          = t 'common.time.ago', time: ( time_ago_in_words (Time.now - order.created_at).seconds.from_now )
  .panel-collapse.collapse{id: "order-card-#{order_token}", class: ('in' if collapse_in)}
    .panel-body
      .row
        .col-md-6
          %dl.dl-horizontal
            %dt= t 'orders.card.recipient_info'
            - if order.transport
              %dd= Transport.human_attribute_name 'recipient_name'
              %dd= order.transport.recipient_name
              %dd= Transport.human_attribute_name 'recipient_address'
              %dd= order.transport.recipient_address
              %dd= Transport.human_attribute_name 'recipient_phone'
              %dd= order.transport.recipient_phone

            %dt= Order.human_attribute_name 'customer_message'
            %dd= order.customer_message

            %dt= t 'orders.card.payment_state'
            %dd
              / TODO currently only handle situations where one order got only one payment
              - payment = order.payment
              = locale_state 'payment', payment.aasm_state
            - if payment.may_pay? and action_name != 'pay'
              %dd= link_to (t 'orders.new.pay'), (pay_order_path order), class: 'btn btn-default btn-sm'
            - if payment.aasm_state != 'initialized'
              %dt= Payment.human_attribute_name 'pay_method'
              %dd= t "payments.method.#{payment.pay_method}"

            %dt= t 'orders.card.transport_state'
            %dd= locale_state 'transport', order.transport.aasm_state #TODO

        .col-md-6
          %table.table.table-hover
            %tbody
              - order.cart[:items].each do |i|
                %tr
                  - case i[:type]
                  - when 'product'
                    %td.cover
                      .cover{style: "background-image: url(#{background_image_url i[:product].cover})"}
                    %td.name= i[:product].name
                    %td.price= to_sg_dollar i[:price]
                    %td.other
            %tfoot
              %tr
                %td
                %td
                %td.price= to_sg_dollar order.cart[:total_price]
                %td

app/views/shared/cards/_product.html.haml
%a.product-card{href: main_app.product_path(product)}
  .product-card
    - unless product.ribbon.empty?
      .ribbon-wrapper
        .ribbon= product.ribbon
    .card-image
      = image_tag product.cover
    .card-header
      = product.name
    .card-content
      = simple_format product.description.truncate(140) unless product.description.nil?
    .card-stats
      %ul.list-unstyled.list-inline
        %li.price
          = to_sg_dollar product.price
        %li.likes
          = product.get_likes.size
          %span
            %i.fa.fa-heart
        %li.comments
          = product.comments.size
          %span
            %i.fa.fa-comments-o
