config/routes.rb
Ationsg::Application.routes.draw do

  scope "(:locale)", locale: /en|zh-CN/ do
    # devise
    devise_scope :user do
      # oauth
      get 'users/oauth_bind' => 'oauth_bind#new_from_oauth', as: :oauth_bind_new
      post 'users/oauth_bind' => 'oauth_bind#bind_with_oauth'

      # registration
      get 'users/sign_up' => 'devise/registrations#new', as: :new_user_registration
      post 'users' => 'devise/registrations#create', as: :user_registration
    end

    # products
    resources :products, only: [:show] do
      get 'like' => 'products#like', as: :like
      get 'unlike' => 'products#unlike', as: :unlike
    end

    resources :comments, only: [:show, :new, :create]

    # categories
    resources :categories, only: [:show]

    # cart
    get 'cart' => 'cart#show', as: :cart
    get 'cart/partial' => 'cart#partial', as: :cart_partial

    # orders
    resources :orders, only: [:new, :create, :show]
    get 'orders/:id/pay' => 'orders#pay', as: :pay_order

    # payments
    # resources :payments, only: [:create]
    get 'payments/new/order/:order_id/method/:method' => 'payments#create', as: :create_payment

    # cards
    get 'cards/:card_id/recharge' => 'recharge_payments#new', as: :recharge_card
    resources :recharge_payments, only: [:new, :create]

    # my
    get 'my' => 'my#info'
    get 'my/info' => 'my#info', as: :my_info
    patch 'my/info' => 'my#info_update', as: :udpate_my_info
    get 'my/orders' => 'my#orders', as: :my_orders
    get 'my/addresses' => 'my#addresses', as: :my_addresses
    get 'my/payments' => 'my#payments', as: :my_payments
    get 'my/liked' => 'my#liked', as: :my_liked
    get 'my/comments' => 'my#comments', as: :my_comments
    get 'my/cards' => 'my#cards', as: :my_cards

    # static pages & root
    resources :pages, only: [:show]

  end

  # admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # omniauth doesnot support dynamic routing with locale
  devise_for :users, controllers: { omniauth_callbacks: 'authentications' }, skip: [:registrations]

  get "/:locale" => 'pages#show', id: 'home'
  root 'pages#show', id: 'home'  

end

app/models/card.rb
class Card < ActiveRecord::Base
  # validations
  validates :balance, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # associations
  belongs_to :user

  def pay(amount)
    return false unless self.balance >= amount
    self.balance -= amount
    self.save
  end

  def recharge(amount)
    self.balance += amount
    self.save!
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
end

app/views/cards/_order.html.haml
- order_token = SecureRandom.hex(10)
.order-card.panel.panel-default
  .panel-heading
    .panel-title
      %a{"data-parent" => ".order-cards", "data-toggle" => "collapse", href: "#order-card-#{order_token}"}
        %i.fa.fa-caret-square-o-down
          = to_sg_dollar order.cart[:total_price]
          ,
          = t 'common.time.created_at'
          = t 'common.time.ago', time: ( time_ago_in_words (Time.now - order.created_at).seconds.from_now )
  .panel-collapse.collapse{id: "order-card-#{order_token}", class: ('in' if collapse_in)}
    .panel-body
      .row
        .col-md-4
          %dl.dl-horizontal
            %dt= t 'orders.card.recipient_info'
            - if order.transport
              %dd= Transport.human_attribute_name 'recipient_name'
              %dd= order.transport.recipient_name
              %dd= Transport.human_attribute_name 'recipient_address'
              %dd= order.transport.recipient_address
              %dd= Transport.human_attribute_name 'recipient_phone'
              %dd= order.transport.recipient_phone

            %dt= Order.human_attribute_name 'customer_message'
            %dd= order.customer_message

            %dt= t 'orders.card.payment_state'
            %dd
              - if order.payments.empty?
                = locale_state 'payment', 'initialized'
              - else
                = locale_state 'payment', order.payments.last.aasm_state
            / TODO currently only handle situations where one order got only one payment
            / TODO button to pay if not paid and action is not pay, or use a var to control wheater to show the button

            %dt= t 'orders.card.transport_state'
            %dd= locale_state 'transport', order.transport.aasm_state #TODO

        .col-md-8
          %table.table.table-hover
            %tbody
              - order.cart[:items].each do |i|
                %tr
                  - case i[:type]
                  - when 'product'
                    %td.cover
                      .cover{style: "background-image: url(#{background_image_url i[:product].cover})"}
                    %td.name= i[:product].name
                    %td.price= to_sg_dollar i[:price]
                    %td.other
            %tfoot
              %tr
                %td
                %td
                %td.price= to_sg_dollar order.cart[:total_price]
                %td

app/views/cards/_product.html.haml
%a.product-card{href: main_app.product_path(product)}
  .product-card
    .ribbon-wrapper
      .ribbon NEW
    .card-image
      = image_tag product.cover
    .card-header
      = product.name
    .card-content
      = simple_format product.description.truncate(140)
    .card-stats
      %ul
        %li
          = product.get_likes.size
          %span Likes
        %li
          / TODO
          298
          %span Sold

app/views/cards/_show.html.haml
.card-show.item
  %aside
    .avatar
      %i.fa.fa-credit-card      
  .content
    %form.form-horizontal
      .form-group
        %label.col-sm-2.control-label
          = Card.human_attribute_name 'id'
        .col-sm-10
          %p.form-control-static= card.id
      .form-group
        %label.col-sm-2.control-label
          = Card.human_attribute_name 'balance'
        .col-sm-10
          %p.form-control-static= to_sg_dollar card.balance
      .form-group
        .col-sm-offset-2.col-sm-10
          = link_to (t 'cards.recharge'), recharge_card_path(card), class: 'btn btn-primary'